language: python
install:
 - pip install tox 
 - pip install -U -r requirements.txt -r test-requirements.txt git+https://github.com/lxc/pylxd#egg=pylxd git+https://github.com/openstack/nova#egg=nova
before_script: flake8 --ignore=E123,E125,H904,H405,H404,H305,H306,H307
script: tox
cache:
    directories:
        - $HOME/.cache/pip
